### PR TITLE
GCC 4.7x

### PR DESCRIPTION
**Pull request by trizna**
changes for compilation with gcc 4.7

### CODE REVIEW

**Comment by arobenko** [comment]
Hi there,
Why do you think there is a need to support gcc4.7? It's quite old and it doesn't have full C++11 support. I don't really want to promise its long term support. At this moment I'm testing the build with gcc5.4, gcc6.0, clang3.9 and VS2015.
Are you using gcc4.7 to compile some real project and would like to be able to use COMMS library as well?

**Comment by trizna** [comment]
I try use comm library in embedded device. It based on ARM processor and managed by linux 3.4. Linux versions older than 3.18 can't be compiled gcc 5.x. Use diferent gcc for   different parts of project is not too good...

**Comment by arobenko** [comment]
OK, I'll try to support earlier version of gcc with next release.

**Comment by trizna** [comment]
Thank you :)

**Comment by arobenko** [comment]
Hi there (what's your name by the way?),
I've managed to get my CommsChampion project compiled with g++-4.8.5. The "develop" branch contains all the necessary changes (but the usage documentation hasn't been updated yet).
My question is: do you really need support for g++-4.7? 4.8 is much more C++11 friendly and you can compile your linux kernel with gcc-4.8 as well. I try to compile the project with g++-4.7 and get some silly errors, which I'm a bit reluctant to fix. The required fixes will make my code "dirtier", such as having type information duplicated in the same statement.

If you're willing to migrate to gcc-4.8, I may have the updated documentation ready for you tomorrow.

Regards,
Alex

**Comment by arobenko** [comment]
The "develop" branch contains all the changes to support both gcc4.7 and gcc4.8. Can you test whether it works for you. I'd like to do the next release in about a week or so?

**Comment by arobenko** [comment]
Support for gcc v4.7 - v4.9 was implemented in v0.20 release

**Comment by trizna** [comment]
Hi, Alex
I spent my vacation in connectionless place, and coud't answer you. Now I home, and will try new release in few days. Vitaly.

**Pull request closed without merging**
