### PR TITLE
examples: fix minor typo

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Happen to notice it while reading the example doc.

### CODE REVIEW

**Comment by arobenko** [comment]
Thanks, I'll merge it before the next release

**Comment by arobenko** [comment]
Fixed in recent v2.2.1 release

**Comment by gavanderhoorn** [comment]
I see no merge @arobenko?

**Comment by arobenko** [comment]
I do my development on "develop" branch, "master one used for releases only. I merged you updates manually a couple of weeks ago.

**Pull request closed without merging**
